spring:
  application:
    name: Resume-Z
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    platform: mysql
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dr_schema?createDatabaseIfNotExist=true
    username:
    password:
    hikari:
      auto-commit: true
    data: classpath*:data/data.sql

server:
  compression:
    enabled: true
  port: 8080